# Generated by Django 4.0.1 on 2022-01-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.CharField(max_length=255)),
                ("latitude", models.CharField(max_length=255)),
                ("longitude", models.CharField(max_length=255)),
                ("datastream", models.CharField(max_length=255)),
                ("ip_address", models.GenericIPAddressField()),
                ("timestamp", models.TimeField()),
            ],
        ),
    ]
