# Generated by Django 4.0.1 on 2022-01-06 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
