# Generated by Django 4.0.1 on 2022-01-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_staff_ip_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="timestamp",
            field=models.DateTimeField(),
        ),
    ]
